### ISSUE TITLE
Extensions as reference?

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine#16]
Unless I'm making any mistake, right now the extensions are being inserted (as a copy) in the preset. What do you think about instead passing it as reference?

For example, when adding a chat wheel from extension library, it will refer it with an ID. So when the extension is modified, the preset is updated.

This way, we can move our chat-wheels/cycles as extension and not maintain the same thing in preset also.

**Comment by FlorianWendelborn** [comment]
@crimsonvspurple yeah, I was actually thinking about that. However, I don't want to implement this yet, since there are planned changes to the whole preset layout to allow per-hero-layouts and named/grouped layouts in general. The code needed for both will probably overlap and make the already complicated process of updating the preset to allow more layouts more complicated later on.

**Comment by crimsonvspurple** [comment]
**Personally**, I think built-in per hero layout is enough and spending time on this feature is not worth it. Some of the things of the built-in system cant even be done using autoexec. For example, when you are controlling two heroes or playing chen with neutral creeps. The game can auto change hotkey on the fly based on which unit you select; autoexec cant.

**Comment by FlorianWendelborn** [comment]
@crimsonvspurple the thing is, this would also allow some things which aren't possible without autoexec. For example: Hero-specific settings like autoAttack on and all the micro-related stuff. Also I may be able to allow Manta to also change hotkeys based on which unit you select. That would require a Manta-client though, but that's something I want to do anyway.
